-- ============================================================
-- TABLE: companies
--
-- Purpose:
-- Stores one record for every company I want to monitor.
-- A company is the parent entity because it can have many jobs
-- and many networking contacts.
-- ============================================================

CREATE TABLE companies (

    -- Primary Key
    -- Unique identifier
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Every company must have a name.
    company_name TEXT NOT NULL,

    website_url TEXT,

    -- URL to the careers page that will eventually be monitored.
    career_page_url TEXT,

    industry TEXT,

    -- Approximate employee count.
    -- Desiring to target companies of a smaller size
  employee_size_min INTEGER,
  employee_size_max INTEGER,

    -- Most of my target companies are remote-first.
    -- Default to TRUE unless I explicitly change it.
    remote_first BOOLEAN NOT NULL DEFAULT TRUE,

    -- Priority helps determine how aggressively I monitor a company.
    -- Examples:
    -- High = Check frequently
    -- Medium = Good opportunity
    -- Low = Nice-to-have
    priority TEXT NOT NULL DEFAULT 'Medium',


    notes TEXT,

    -- Automatically records when the company was added.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    ------------------------------------------------------------
    -- Constraints
    ------------------------------------------------------------

    -- Prevent duplicate company names.
    CONSTRAINT companies_name_unique UNIQUE (company_name),

    -- Employee count cannot be negative.
    CONSTRAINT companies_employee_count_positive
        CHECK (employee_size_min IS NULL OR employee_size_min >= 0),

    -- Only allow three priority values.
    CONSTRAINT companies_priority_valid
        CHECK (priority IN ('High', 'Medium', 'Low'))

);

