CREATE TABLE applications (
  application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  job_id BIGINT NOT NULL,
  
  --TIMESTAMPTZ instead of date since I want to know the time when I applied too
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  --Copy and paste resume 
  resume_version TEXT NOT NULL, 

  --Defaukts to applied but have other options too below
  application_status TEXT NOT NULL DEFAULT 'APPLIED',

  follow_up_at DATE, 

  cover_letter_used BOOLEAN,

  application_method TEXT,

  notes TEXT,

  created_at TIMESTAMPTZ,

--Foreign Key is the job_id
 CONSTRAINT applications_job_foreign_key 
  FOREIGN KEY (job_id)
  REFERENCES jobs(job_id),

--There can only be one job per one application
 CONSTRAINT applications_job_unique
  UNIQUE (job_id),
  
  --Options for applied_status
  CONSTRAINT applications_status_valid
    CHECK (
      application_status IN (
        'APPLIED',
        'INTERVIEW',
        'REJECTED',
        'OFFER'
      )
    )

)
