CREATE table contacts (
  --The goal for this is to allow me to reach out to the appropiate contact and keep track of who they ae all in one place
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  company_id BIGINT NOT NULL,

  first_name TEXT NOT NULL,

  last_name TEXT NOT NULL,

  job_title TEXT, 

  contact_platform TEXT NOT NULL,

  contact_value TEXT NOT NULL,
  
  notes TEXT,

  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

--FOREIGN KEY is the company_id since each contact can help with one company for several jobs
CONSTRAINT contact_table_foreign_id
  FOREIGN KEY (company_id)
  REFERENCES companies(company_id)

)
