CREATE TABLE experiences (
  --The goal is for this to make a solid list of experiences so AI can use them to create resume

  experience_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  job_id BIGINT NOT NULL,
  
  company_name TEXT NOT NULL, 

  job_title TEXT NOT NULL,

  start_date DATE NOT NULL,

  end_date DATE NOT NULL, 
  
  location TEXT NOT null,

CONSTRAINT company_name_foreign_key 
  FOREIGN KEY (company_name)
  REFERENCES companies(company_name),

CONSTRAINT job_title_foreign_key 
  FOREIGN KEY (job_id)
  REFERENCES jobs(job_id)

)
