-- ============================================================
-- TABLE: jobs
--
-- Purpose:
-- Stores one record for each job opportunity I want to track.
-- This table stores information about the opportunity itself.
-- ============================================================

CREATE TABLE jobs (

    -- Primary key.
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Foreign key connecting this job to the company that posted it.
    -- The company must already exist in the companies table.
    company_id BIGINT NOT NULL,

    job_title TEXT NOT NULL,

    job_url TEXT NOT NULL,

    -- Examples: Operations, Finance, Product, Client Services.
    department TEXT,

    -- Examples: Remote, Savannah, GA, or United States.
    location TEXT,

    -- Most jobs I track will be remote.
    -- Defaults to TRUE unless I specify otherwise.
    remote BOOLEAN NOT NULL DEFAULT TRUE,

    -- The type of employment offered.
    -- I mainly want full-time or part-time roles,
    -- but contract is included for tracking when needed.
    employment_type TEXT NOT NULL DEFAULT 'Full-Time',

    -- Minimum advertised annual salary.
    -- Can remain blank if the employer does not list compensation.
    salary_min NUMERIC(12, 2),

    -- Maximum advertised annual salary.
    -- Can remain blank if the employer does not list compensation.
    salary_max NUMERIC(12, 2),

    -- The date and time the employer says the job was posted.
    -- This helps me prioritize jobs posted on the same day.
    posted_at TIMESTAMPTZ,

    -- The date and time my system first discovered the job.
    -- Useful when the employer does not provide an exact posting time.
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- This will later be used for AI matching and resume tailoring.
    job_description TEXT,

    -- A score from 0 to 100 showing how closely the job matches
    -- my experience, preferences, and qualifications.
    match_score NUMERIC(5, 2),

    -- Describes the current availability of the job posting.
    -- This is different from my application status.
    job_status TEXT NOT NULL DEFAULT 'New',

    -- Additional notes about the opportunity.
    notes TEXT,

    -- Automatically records when the database record was created.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    ------------------------------------------------------------
    -- Relationships and validation rules
    ------------------------------------------------------------

    -- Connects company_id to the primary key in companies.
    -- Prevents a job from being assigned to a company that
    -- does not exist in the companies table.
    CONSTRAINT jobs_company_foreign_key
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id),

    -- Prevents the same job URL from being added more than once.
    CONSTRAINT jobs_url_unique
        UNIQUE (job_url),

    -- Only permits employment types that fit my search criteria.
    CONSTRAINT jobs_employment_type_valid
        CHECK (
            employment_type IN (
                'Full-Time',
                'Part-Time',
                'Contract'
            )
        ),

    -- Prevents negative salary values.
    CONSTRAINT jobs_salary_min_valid
        CHECK (salary_min IS NULL OR salary_min >= 0),

    CONSTRAINT jobs_salary_max_valid
        CHECK (salary_max IS NULL OR salary_max >= 0),

    -- Ensures the maximum salary is not lower than the minimum.
    CONSTRAINT jobs_salary_range_valid
        CHECK (
            salary_min IS NULL
            OR salary_max IS NULL
            OR salary_max >= salary_min
        ),

    -- Match scores must remain between 0 and 100.
    CONSTRAINT jobs_match_score_valid
        CHECK (
            match_score IS NULL
            OR match_score BETWEEN 0 AND 100
        ),

    -- Describes whether the posting is new, saved, skipped,
    -- expired, or closed.
    CONSTRAINT jobs_status_valid
        CHECK (
            job_status IN (
                'New',
                'Saved',
                'Skipped',
                'Expired',
                'Closed'
            )
        )
);
