CREATE TABLE resumes (
  --The goal is for this to keep track of all the resume versions I am using. AI should be creating these versions that are ATS friendly following the Google xyz format. I should have to do minimal edits before submitting it.

  resume_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  docx_url TEXT,

  pdf_url TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
