-- This will include misc details to go into my resume that was not covered in the other tables

CREATE TABLE profile_details (
  profile_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- education/certification, system, programming language
  profile_type TEXT NOT NULL,

  profile_institution_name TEXT,

  profile_institution_subject TEXT,

  profile_degree_or_certification_level TEXT,

  profile_institution_start_date DATE,

  profile_institution_end_date DATE,

  profile_system_name TEXT,

  profile_programming_language TEXT

)
